"""Rebuilds the Tomatin wordmark as vector paths (the live site only ships a 170x47 PNG).
Letters come from Marcellus (OFL), the closest open match to the flared Roman capitals of the real logo.
Outputs lib/logo-paths.ts: one path per letter so the preloader can build the mark letter by letter.
Run: python3 scripts/build-logo.py   (needs fonttools)"""
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
import json, os

font = TTFont(os.path.join(os.path.dirname(__file__), "fonts/Marcellus-Regular.ttf"))
gs, cmap, hmtx = font.getGlyphSet(), font.getBestCmap(), font["hmtx"]
upm = font["head"].unitsPerEm

def word(text, size, track, y, x0=0.0):
    """Returns ([path per letter], width, [x of each letter]) laid out left to right, baseline at y."""
    scale, x, out, xs = size / upm, x0, [], []
    for ch in text:
        name = cmap[ord(ch)]
        pen = SVGPathPen(gs, ntos=lambda v: f"{v:.1f}")
        gs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, x, y)))
        out.append(pen.getCommands()); xs.append(x)
        x += hmtx[name][0] * scale + track
    return out, x - track - x0, xs

TOP, TRACK_TOP, BASE = 100, 3, 78
top, top_w, top_x = word("TOMATIN", TOP, TRACK_TOP, BASE)
SUB, TRACK_SUB = 27, 11
sub_w = word("DISTILLERY", SUB, TRACK_SUB, 140)[1]
off = (top_w - sub_w) / 2
sub, _, _ = word("DISTILLERY", SUB, TRACK_SUB, 140, off)

# Swash on the A (the real logo sweeps the crossbar out to the left, over the M/A gap). Anchored to the A's own position.
ax = top_x[3] + 6
yb = BASE - 26  # crossbar height
swash = f"M{ax+14:.1f} {yb:.1f}C{ax+6:.1f} {yb-9:.1f} {ax-8:.1f} {yb-11:.1f} {ax-20:.1f} {yb-6:.1f}C{ax-9:.1f} {yb-5:.1f} {ax-1:.1f} {yb-1:.1f} {ax+4:.1f} {yb+5:.1f}Z"
rule = f"M{off:.1f} 106H{off+sub_w:.1f}"
data = {"w": round(top_w, 1), "h": 146, "top": top, "sub": sub, "swash": swash, "rule": rule}
open(os.path.join(os.path.dirname(__file__), "../lib/logo-paths.ts"), "w").write(
    "// Generated by scripts/build-logo.py. Do not edit by hand.\nexport const logo = " + json.dumps(data) + " as const;\n")
print("wordmark", data["w"], "x", data["h"])
